Repository jimaeda/BlooDiscounts, pull requests merged in 2019-10, with the labels that each got.

#17 Hotfix - Compilação do application.js
  Procfile
  app/javascript/packs/application.js
Labels: bug, review needed

#18 Hotfix - Sign out not working
  .travis.yml
  app/views/layouts/application.html.erb
  app/views/layouts/selecao_user.html
  config/webpack/environment.js
  db/migrate/20190925103824_add_birth_date_blood_type_to_users.rb
  package.json
  yarn.lock
Labels: bug, review needed

#20 Adição de informação do usuário e ajustes
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/user/pontos.html.erb
  app/views/user/profile.html.erb
  config/environments/development.rb
  db/migrate/20191017175850_add_info_to_users.rb
  db/schema.rb
Labels: enhancement, review needed

#19 Admin - Login e tela de opções
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/assets/stylesheets/sessions.scss
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/models/admin.rb
  app/views/admins/_form.html.erb
  app/views/admins/edit.html.erb
  app/views/admins/profile.html.erb
  app/views/admins/show.html.erb
  app/views/sessions/new.html.erb
  config/application.rb
  config/environment.rb
  config/environments/test.rb
  config/routes.rb
  db/migrate/20191013210914_add_password_digest_to_admins.rb
  db/schema.rb
  features/admin_login.feature
  features/step_definitions/admin_login_steps.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/helpers/sessions_helper_spec.rb
  spec/rails_helper.rb
  spec/views/admins/edit.html.erb_spec.rb
  spec/views/admins/profile.html.erb_spec.rb
  spec/views/admins/show.html.erb_spec.rb
  spec/views/pages/home.html.erb_spec.rb
  spec/views/sessions/new.html.erb_spec.rb
Labels: feature, review needed

#25 Teste de login do usuário
  .rspec
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/locales/devise.pt-BR.yml
  features/admin_login.feature
  features/login.feature
  features/step_definitions/admin_login_steps.rb
  features/step_definitions/login_steps.rb
  features/support/env.rb
  spec/factories.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
Labels: enhancement, review needed
