Repository jimaeda/BlooDiscounts, pull requests merged in 2019-11, with the labels that each got.

#33 Edição nos hospitais
  Gemfile
  app/controllers/hospitals_controller.rb
  app/models/hospital.rb
  app/views/hospitals/_form.html.erb
  app/views/hospitals/edit.html.erb
  app/views/hospitals/index.html.erb
  app/views/hospitals/new.html.erb
  app/views/hospitals/show.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/application.html.erb
  config/application.rb
  db/migrate/20191106002611_add_lattitude_longitude_to_hospitals.rb
  db/schema.rb
  features/new_hospital.feature
  features/step_definitions/web_steps.rb
  spec/views/hospitals/edit.html.erb_spec.rb
  spec/views/hospitals/index.html.erb_spec.rb
  spec/views/hospitals/show.html.erb_spec.rb
Labels: enhancement, review needed

#36 Hotfix - Chave de API
  config/credentials.yml.enc
Labels: help wanted

#40 Features
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/assets/stylesheets/rewards.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/admins_controller.rb
  app/controllers/rewards_controller.rb
  app/controllers/stores_controller.rb
  app/helpers/rewards_helper.rb
  app/models/reward.rb
  app/models/store.rb
  app/views/admins/index.html.erb
  app/views/admins/new.html.erb
  app/views/admins/profile.html.erb
  app/views/admins/register_donation.html.erb
  app/views/rewards/_form.html.erb
  app/views/rewards/_reward.json.jbuilder
  app/views/rewards/edit.html.erb
  app/views/rewards/index.html.erb
  app/views/rewards/index.json.jbuilder
  app/views/rewards/new.html.erb
  app/views/rewards/show.html.erb
  app/views/rewards/show.json.jbuilder
  app/views/stores/_form.html.erb
  app/views/stores/edit.html.erb
  app/views/stores/index.html.erb
  app/views/stores/new.html.erb
  config/credentials.yml.enc
  config/routes.rb
  db/migrate/20191110173019_add_store_id_to_reward.rb
  db/schema.rb
  features/admin_edit_profile.feature
  features/admin_login.feature
  features/hospital_new.feature
  features/reward.feature
  features/reward_new.feature
  features/step_definitions/web_steps.rb
  features/store_new.feature
  features/user_edit_profile.feature
  features/user_sign_up.feature
  spec/controllers/rewards_controller_spec.rb
  spec/controllers/stores_controller_spec.rb
  spec/helpers/rewards_helper_spec.rb
  spec/requests/admins_spec.rb
  spec/requests/rewards_spec.rb
  spec/routing/rewards_routing_spec.rb
  spec/views/admins/index.html.erb_spec.rb
  spec/views/rewards/edit.html.erb_spec.rb
  spec/views/rewards/index.html.erb_spec.rb
  spec/views/rewards/new.html.erb_spec.rb
  spec/views/rewards/show.html.erb_spec.rb
  spec/views/stores/index.html.erb_spec.rb
Labels: feature, review needed

#43 Resgate de Descontos
  Gemfile
  Gemfile.lock
  app/controllers/rewards_controller.rb
  app/controllers/user_controller.rb
  app/javascript/packs/application.js
  app/views/devise/registrations/edit.html.erb
  app/views/hospitals/show.html.erb
  app/views/rewards/index.html.erb
  app/views/rewards/show.html.erb
  app/views/user/points.html.erb
  app/views/user/profile.html.erb
  app/views/user/show.html.erb
  config/routes.rb
  features/hospital_new.feature
  features/step_definitions/web_steps.rb
  features/user_edit_js_validation.feature
  features/user_edit_profile.feature
  spec/views/user/show.html.erb_spec.rb
Labels: enhancement, review needed
